# Generated by Django 2.2.10 on 2020-02-19 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
                ('blog_post_text', models.TextField()),
                ('blog_image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
